project:
  type: website
  output-dir: docs
filters:
  - fontawesome
website:
  site-url: https://eco-sosa.github.io/Brandon-Sosa.github.io/
  title: "Brandon Sosa"
  favicon: images/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: photos.qmd
        text: Media
      - href: F_C.qmd
        text: Collaborators & Funding        
    right:
      - icon: link
        href: https://bsky.app/profile/eco-sosa.bsky.social
        text: BlueSky
        target: _blank
      - icon: github
        href: https://github.com/eco-sosa
        target: _blank
      - icon: instagram
        href: https://instagram.com/eco.sosa
        target: _blank
      - icon: linkedin
        href: https://linkedin.com/in/bsos
        target: _blank
  page-footer:
    center: |
      <span style="opacity:0.9;">
        Built proudly using <a href="https://quarto.org" target="_blank">Quarto</a> 
        in <a href="https://posit.co/products/open-source/rstudio/" target="_blank">RStudio</a>.
        &nbsp;•&nbsp;
        <a href="mailto:bsosa012@fiu.edu">bsosa012@fiu.edu</a>
      </span>
format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 200px
    theme: 
      light: light.scss
      dark: dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false